#
# Site settings
#

version: 1.1

title: OfflineIMAP community's website
email: offlineimap-project@lists.alioth.debian.org
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://offlineimap.org"
description: > # this means it ignores newlines until next key
  OfflineIMAP community's website.

#
# Build settings
#
highlighter: pygments
github: [Repository metadata]
paginate: 10

markdown: kramdown
kramdown:
  input: GFM

#
# Posts
#
excerpt_separator: <!--more-->

github_username: OfflineIMAP
twitter_username: OfflineImap

collections:
  doc:
    output: true
